### ISSUE TITLE
Support build segwit transaction

### ISSUE THREAD

**Issue by SFzxc** [anicdh/bitcoin_flutter#26]
- PRs: https://github.com/anicdh/bitcoin_flutter/pull/25

**Comment by SFzxc** [comment]
Lunar new year now, Will come back soon

**Comment by RohanKapurDEV** [comment]
Hey guys, any progress here?

**Comment by RohanKapurDEV** [comment]
Hey I understand you may be busy. How can I help develop the Native Segwit Transaction Builder?

Specifically:

1) How much is already done?
2) What is left to port over from BitcoinJS?

If someone writes a detailed answer outlining exactly the parts i need to port over, i will try to help as much as possible but I'm not sure how much has been done since there is no documentation. Give me the way forward and I'll try my best.

**Comment by SFzxc** [comment]
@RohanKapurDEV Sorry, i'm so busy now, i added test to cover segwit tx cases. you just need to write code to pass all testcase.
Run `pub run test` to see which testcase is failed

**Comment by RohanKapurDEV** [comment]
I have been reviewing the files. Finding this rather difficult honestly. What do you think about me trying to integrate PSBT for bitcoin-flutter, seems a bit more future proof anyway, no?

**Comment by SFzxc** [comment]
@RohanKapurDEV Sure, PSBT must have soon, appreciate it!

**Comment by RohanKapurDEV** [comment]
So I've started the skeleton of the PSBT in dart. I'm going to attempt to port over the BIP174 library from Alex Bosworth here: https://github.com/alexbosworth/psbt.

However, since this will likely take me a while (a few months at the least), do you think you could continue to work on the segwit support for the transactionbuilder since you've already started. We may end up with a more robust library if we have both.

Thanks, let me know.

**Comment by longhoangwkm** [comment]
i will, but quite slow

**Comment by longhoangwkm** [comment]
@RohanKapurDEV btw, Using this one https://github.com/bitcoinjs/bip174 not https://github.com/alexbosworth/psbt.

**Comment by longhoangwkm** [comment]
Moved to here https://github.com/anicdh/bitcoin_flutter/issues/27
